
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _new = 13;
  public static final int _plus = 22;
  public static final int _assignop = 37;
  public static final int _mod = 27;
  public static final int _println = 16;
  public static final int _greater = 30;
  public static final int _return = 18;
  public static final int _leftbrace = 45;
  public static final int _minus = 23;
  public static final int _null = 15;
  public static final int _rightbracket = 44;
  public static final int _readln = 17;
  public static final int _void = 20;
  public static final int _comma = 39;
  public static final int _class = 4;
  public static final int _multiplication = 25;
  public static final int _else = 6;
  public static final int _division = 26;
  public static final int _boolean = 2;
  public static final int _equal = 32;
  public static final int _rightbrace = 46;
  public static final int _leftbracket = 43;
  public static final int EOF = 0;
  public static final int _string = 19;
  public static final int error = 1;
  public static final int _break = 3;
  public static final int _interface = 12;
  public static final int _or = 35;
  public static final int _leftparen = 41;
  public static final int _notequal = 33;
  public static final int _semicolon = 38;
  public static final int _if = 9;
  public static final int _id = 50;
  public static final int _while = 21;
  public static final int _lessequal = 29;
  public static final int _doubleconstant = 48;
  public static final int _int = 11;
  public static final int _implements = 10;
  public static final int _greaterequal = 31;
  public static final int _period = 40;
  public static final int _uminus = 24;
  public static final int _extends = 7;
  public static final int _for = 8;
  public static final int _not = 36;
  public static final int _and = 34;
  public static final int _double = 5;
  public static final int _newarray = 14;
  public static final int _stringconstant = 49;
  public static final int _intconstant = 47;
  public static final int _booleanconstant = 51;
  public static final int _less = 28;
  public static final int _rightparen = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "_boolean",
  "_break",
  "_class",
  "_double",
  "_else",
  "_extends",
  "_for",
  "_if",
  "_implements",
  "_int",
  "_interface",
  "_new",
  "_newarray",
  "_null",
  "_println",
  "_readln",
  "_return",
  "_string",
  "_void",
  "_while",
  "_plus",
  "_minus",
  "_uminus",
  "_multiplication",
  "_division",
  "_mod",
  "_less",
  "_lessequal",
  "_greater",
  "_greaterequal",
  "_equal",
  "_notequal",
  "_and",
  "_or",
  "_not",
  "_assignop",
  "_semicolon",
  "_comma",
  "_period",
  "_leftparen",
  "_rightparen",
  "_leftbracket",
  "_rightbracket",
  "_leftbrace",
  "_rightbrace",
  "_intconstant",
  "_doubleconstant",
  "_stringconstant",
  "_id",
  "_booleanconstant"
  };
}

